### ISSUE TITLE
try to run example crash 

### ISSUE THREAD

**Issue by juicechu** [brunoga/robomaster#1]
```
go run main.go             
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/bin/ld: /usr/local/lib/libavcodec.a(flashsv.o): undefined reference to symbol 'inflateEnd'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
i have install gocv.io
```
go run ./cmd/version/main.go
gocv version: 0.23.0
opencv lib version: 4.3.0
```

**Comment by brunoga** [comment]
Should be fixed now. It is weird that it works on my development desktop without -lz. Please try again and let me know how it goes.

**Comment by juicechu** [comment]
Thank for you help ! But it still crash after update lastest code.
System: Ubuntu 18.04.4
Kernel: 4.15.0-101-generic

```
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/bin/ld: /usr/local/lib/libavcodec.a(tiff.o): undefined reference to symbol 'lzma_stream_decoder@@XZ_5.0'
//lib/x86_64-linux-gnu/liblzma.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
I had read sdk code and try to understand it.
Maybe i should start to study opencv and read opencv doc. 
Thank for contribution, i learn a lot

**Comment by brunoga** [comment]
This is really weird but I guess one explanation would be that you are making use of statically linked libraries for libav. Anyway, I added the other missing library. Can you pull and try again?

**Comment by juicechu** [comment]
Yes, i have pull the latest code and run again. Some other error happen,  I found this problem maybe cause by ffmpeg-4.1 .
So i decide to remove ffmpeg and run it later.
```
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_subpacket':
/home/juice/Downloads/ffmpeg-4.1/libavcodec/opusdec.c:346: undefined reference to `swr_is_initialized'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_frame':
/home/juice/Downloads/ffmpeg-4.1/libavcodec/opusdec.c:187: undefined reference to `swr_is_initialized'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_init_resample':
/home/juice/Downloads/ffmpeg-4.1/libavcodec/opusdec.c:135: undefined reference to `swr_init'
/home/juice/Downloads/ffmpeg-4.1/libavcodec/opusdec.c:141: undefined reference to `swr_convert'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_frame':
/home/juice/Downloads/ffmpeg-4.1/libavcodec/opusdec.c:201: undefined reference to `swr_convert'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_flush_resample':
/home/juice/Downloads/ffmpeg-4.1/libavcodec/opusdec.c:89: undefined reference to `swr_convert'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_subpacket':
/home/juice/Downloads/ffmpeg-4.1/libavcodec/opusdec.c:378: undefined reference to `swr_close'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_flush':
/home/juice/Downloads/ffmpeg-4.1/libavcodec/opusdec.c:581: undefined reference to `swr_close'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_close':
/home/juice/Downloads/ffmpeg-4.1/libavcodec/opusdec.c:605: undefined reference to `swr_free'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_init':
/home/juice/Downloads/ffmpeg-4.1/libavcodec/opusdec.c:674: undefined reference to `swr_alloc'
collect2: error: ld returned 1 exit status
```

**Comment by brunoga** [comment]
The errors you are seeing now are definitely due to your setup (why is it
reading livav* libraries from an ffmpeg installed in your Downloads dir?).

If you are willing to get this working, can we try form scratch?

First thing would be to remove this FFMPEG from your downloads dir and
remove any references to it (PATH, library paths, etc). Now uninstall
libavcodec, libswscale and libavutil.

sudo apt remove libavcodec libswscale libavutil

Then reinstall those:

sudo apt install libavcodec libswscale libavutil

Then try again and let me know what happens.

**Comment by brunoga** [comment]
The errors you are seeing now are definitely due to your setup (why is it reading libav* libraries from an ffmpeg installed in your Downloads dir?).

If you are willing to get this working, can we try from scratch?

First thing would be to remove this FFMPEG from your downloads dir and remove any references to it (PATH, library paths, etc). Now uninstall libavcodec, libswscale

**Comment by juicechu** [comment]
Yes, everything is all right after ffmpeg removed. I install ffmpeg from source code complie long time ago.
After that I reinstall ffmpeg from apt and run balltracker,  program running still goods. I did't found any error message again.
So i think problem is solved. Thank you brunoga. I will awalys subscribe learning robomaster sdk and your creativity
